# Generated by Django 4.2.16 on 2024-09-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('PARTIALLY_FILLED', 'PARTIALLY_FILLED'), ('CANCELLED', 'CANCELLED'), ('INSUFFICIENT_FUND', 'INSUFFICIENT_FUND')], default='PENDING', max_length=17),
        ),
    ]
