# Generated by Django 4.2.16 on 2024-09-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('INSUFFICIENT_FUND', 'INSUFFICIENT_FUND'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=17)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
