version: '3.1'

services:
  postgres:
    restart: always
    image: postgres:15.3
    volumes:
      - ../db/postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_SUPER_USER_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    container_name: postgres-trading

  rabbitmq:
    restart: always
    image: rabbitmq:3.11.16
    volumes:
      - ../lib/rabbitmq:/var/lib/rabbitmq
      - ../logs/rabbitmq:/var/log/rabbitmq
      - ../scripts/rabbitmq:/tmp/scripts
    hostname: "rabbitmq-trading"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_DEFAULT_VHOST}"
    ports:
      - "${RABBITMQ_PORT}:5672"
    container_name: rabbitmq-trading

  web:
    restart: always
    build:
      context: ../
    image: web-trading
    volumes:
      - ../:/srv/trader
    container_name: web-trading
    working_dir: "/srv/trader"
    command: "/usr/sbin/sshd -D"