# Generated by Django 4.2.16 on 2024-09-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ticker', models.CharField(max_length=16, unique=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
