# Generated by Django 4.2.16 on 2024-09-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet_running_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('INPROGRESS', 'INPROGRESS'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=10),
        ),
    ]
