# Generated by Django 4.2.16 on 2024-09-16 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0004_alter_wallettransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('wallet', 'stock')},
        ),
    ]
